spring:
  application:
    name: orderservice
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          isolation: READ_COMMITTED
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://orderservice_postgres:5432/order_service_db}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true                                                                                                                                                                                                                ▆
    url: ${POSTGRES_URL:secret}
    user: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD}
  cache:
    cache-names:
      - userInfo
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=3m,recordStats

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8082

application:
  id: ${APPLICATION_CLIENT_ID}
  login: ${APPLICATION_CLIENT_LOGIN}
  secret: ${APPLICATION_CLIENT_SECRET}

  userservice:
    getUserUriUnformatted: ${USRSVC_GET_USER_URI_NOT_FORMATTED:http://userservice:8080/api/v1/users/}
    # smth like ".../users/" , so the UserClient appends the needed userId to the end of the url: ".../users/1"
  authService:
    getServiceAccessTokenUri: ${AUTHSVC_GET_SERVICE_ACCESS_TOKEN_URI:http://authservice:8081/api/v1/auth/service/authenticate}}
  security:
    jwksUrl: ${JWKS_URL:http://authservice:8081/.well-known/jwks.json}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException
      authService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException


  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException