spring:
  application:
    name: orderservice
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          isolation: READ_COMMITTED
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
liquibase:
  change-log: db/changelog/db.changelog-master.yaml
  enabled: true                                                                                                                                                                                                                ▆
  url: ${POSTGRES_URL}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8082